/**
 * Snapshot static file server — generated by web-clone.
 * Zero npm dependencies; uses only Node.js built-in modules.
 *
 * Usage:
 *   node server.js              # serve on port 8080
 *   PORT=3000 node server.js    # custom port
 *
 * Reverse proxy: reads proxy-config.json for origin URL.
 *   - When proxy is enabled, unknown routes are forwarded to the origin
 *     with CORS headers added to the response.
 *   - When proxy is disabled, unknown routes return 404.
 */

const http = require('http');
const fs = require('fs');
const path = require('path');

const PORT = parseInt(process.env.PORT, 10) || 8080;
const ROOT = __dirname;

// ── MIME types ──────────────────────────────────────────────────────
const MIME_TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.js':    'application/javascript; charset=utf-8',
  '.mjs':   'application/javascript; charset=utf-8',
  '.cjs':   'application/javascript; charset=utf-8',
  '.css':   'text/css; charset=utf-8',
  '.json':  'application/json; charset=utf-8',
  '.png':   'image/png',
  '.jpg':   'image/jpeg',
  '.jpeg':  'image/jpeg',
  '.gif':   'image/gif',
  '.webp':  'image/webp',
  '.svg':   'image/svg+xml',
  '.ico':   'image/x-icon',
  '.woff':  'font/woff',
  '.woff2': 'font/woff2',
  '.ttf':   'font/ttf',
  '.otf':   'font/otf',
  '.eot':   'application/vnd.ms-fontobject',
  '.wasm':  'application/wasm',
  '.mp4':   'video/mp4',
  '.webm':  'video/webm',
  '.mp3':   'audio/mpeg',
  '.wav':   'audio/wav',
};

// ── Proxy config ────────────────────────────────────────────────────
let proxyConfig = { originUrl: '', proxyEnabled: false };
const configPath = path.join(ROOT, 'proxy-config.json');
try {
  proxyConfig = JSON.parse(fs.readFileSync(configPath, 'utf8'));
} catch { /* no config — proxy disabled */ }

// ── Reverse proxy helper ────────────────────────────────────────────
function proxyRequest(targetOrigin, req, res) {
  let urlObj;
  try { urlObj = new URL(targetOrigin); } catch {
    res.writeHead(502, { 'Content-Type': 'text/plain; charset=utf-8' });
    res.end('Invalid proxy target origin');
    return;
  }

  const isHttps = urlObj.protocol === 'https:';
  const proxyPath = req.url || '/';
  const lib = isHttps ? require('https') : require('http');

  const proxyOptions = {
    hostname: urlObj.hostname,
    port: urlObj.port || (isHttps ? 443 : 80),
    path: proxyPath,
    method: req.method || 'GET',
    headers: {
      'Host': urlObj.hostname,
    },
    timeout: 30000,
  };

  // Forward key headers that the origin might need
  for (const h of ['accept', 'accept-language', 'user-agent', 'referer', 'content-type', 'content-length', 'cookie']) {
    if (req.headers[h]) proxyOptions.headers[h] = req.headers[h];
  }

  const proxyReq = lib.request(proxyOptions, (proxyRes) => {
    // Add CORS headers to proxied responses
    const headers = {
      ...proxyRes.headers,
      'access-control-allow-origin': '*',
      'access-control-allow-methods': 'GET, POST, OPTIONS',
      'access-control-allow-headers': '*',
    };
    res.writeHead(proxyRes.statusCode || 200, headers);
    proxyRes.pipe(res);
  });

  proxyReq.on('error', (err) => {
    res.writeHead(502, { 'Content-Type': 'text/plain; charset=utf-8' });
    res.end('Proxy Error: ' + err.message);
  });

  proxyReq.on('timeout', () => {
    proxyReq.destroy();
    res.writeHead(504, { 'Content-Type': 'text/plain; charset=utf-8' });
    res.end('Proxy Timeout');
  });

  if (req.method !== 'GET' && req.method !== 'HEAD' && req.method !== 'OPTIONS') {
    req.pipe(proxyReq);
  } else {
    proxyReq.end();
  }
}

// ── Server ──────────────────────────────────────────────────────────
const server = http.createServer((req, res) => {
  // CORS preflight
  if (req.method === 'OPTIONS') {
    res.writeHead(204, {
      'access-control-allow-origin': '*',
      'access-control-allow-methods': 'GET, POST, OPTIONS',
      'access-control-allow-headers': '*',
      'access-control-max-age': '86400',
    });
    res.end();
    return;
  }

  let urlPath = req.url || '/';
  const queryIdx = urlPath.indexOf('?');
  if (queryIdx !== -1) urlPath = urlPath.substring(0, queryIdx);

  // Default to index.html for directory paths
  const filePath = urlPath.endsWith('/')
    ? path.join(ROOT, urlPath, 'index.html')
    : path.join(ROOT, urlPath);

  const ext = path.extname(filePath).toLowerCase();
  const contentType = MIME_TYPES[ext] || 'application/octet-stream';

  // Try static file
  try {
    const stats = fs.statSync(filePath);
    const mtime = stats.mtime.toUTCString();
    const etag = '"' + stats.size + '-' + stats.mtimeMs.toString(16) + '"';

    // Conditional request: If-None-Match
    if (req.headers['if-none-match'] === etag) {
      res.writeHead(304, {
        'etag': etag,
        'last-modified': mtime,
        'cache-control': 'no-cache',
        'access-control-allow-origin': '*',
      });
      res.end();
      return;
    }

    // Conditional request: If-Modified-Since
    if (req.headers['if-modified-since'] === mtime) {
      res.writeHead(304, {
        'etag': etag,
        'last-modified': mtime,
        'cache-control': 'no-cache',
        'access-control-allow-origin': '*',
      });
      res.end();
      return;
    }

    const headers = {
      'Content-Type': contentType,
      'etag': etag,
      'last-modified': mtime,
      'access-control-allow-origin': '*',
    };
    // HTML: no cache; other assets: cache 1 hour
    headers['cache-control'] = ext === '.html' ? 'no-cache' : 'public, max-age=3600';

    res.writeHead(200, headers);
    fs.createReadStream(filePath).pipe(res);
  } catch {
    // File not found → reverse proxy or 404
    if (proxyConfig.proxyEnabled && proxyConfig.originUrl) {
      proxyRequest(proxyConfig.originUrl, req, res);
    } else {
      res.writeHead(404, {
        'Content-Type': 'text/plain',
        'access-control-allow-origin': '*',
      });
      res.end('Not Found');
    }
  }
});

server.listen(PORT, () => {
  console.log('Snapshot served at: http://localhost:' + PORT);
  if (proxyConfig.proxyEnabled && proxyConfig.originUrl) {
    console.log('Proxy origin: ' + proxyConfig.originUrl);
  }
  console.log('Press Ctrl+C to stop.');
});
